name: build output

on:
  push:
    tags:
      - "v[0123].[0-9]+.[0-9]+"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: true

      - name: build outputs
        run: |
          pnpm run generate

      - name: compress outputs
        run: |
          ls ./.output
          tar -czf static.tar.gz ./.output/public

      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            static.tar.gz
          generate_release_notes: true
          draft: true
          prerelease: false
